# 🦔 La Ninna - Docker Compose Configuration

version: '3.8'

services:
  laninna-app:
    build: .
    container_name: laninna-hedgehog-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=release
      - DB_PATH=/data/laninna.db
      - AUTO_MIGRATE=true
      - JWT_SECRET=${JWT_SECRET:-laninna-default-secret-change-in-production}
      - NOTIFICATION_INTERVAL_MINUTES=30
    volumes:
      - laninna_data:/data
      - ./logs:/root/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laninna.rule=Host(`localhost`)"
      - "traefik.http.services.laninna.loadbalancer.server.port=8080"

  # Optional: Add a reverse proxy
  traefik:
    image: traefik:v2.10
    container_name: laninna-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    profiles:
      - proxy

volumes:
  laninna_data:
    driver: local

networks:
  default:
    name: laninna-network