# 🦔 La Ninna - Development Docker Compose

version: '3.8'

services:
  laninna-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: laninna-dev
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=debug
      - DB_PATH=/data/laninna-dev.db
      - AUTO_MIGRATE=true
      - JWT_SECRET=dev-secret-key
      - DEBUG_SQL=true
    volumes:
      - ./:/app
      - laninna_dev_data:/data
      - ./logs:/root/logs
    working_dir: /app
    command: ["air", "-c", ".air.toml"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  laninna_dev_data:
    driver: local