# 🦔 La Ninna - Development Docker Compose

services:
  laninna-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: builder  # Use the builder stage for development
    container_name: laninna-dev
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=debug
      - DB_PATH=/data/laninna-dev.db
      - AUTO_MIGRATE=true
      - JWT_SECRET=dev-secret-key-do-not-use-in-production
      - DEBUG_SQL=true
      - FONTS_PATH=./fonts
      - NOTIFICATION_INTERVAL_MINUTES=30
      - EXPORT_MAX_RECORDS=1000
      - REQUEST_TIMEOUT_SECONDS=30
      - RATE_LIMIT_REQUESTS_PER_MINUTE=100
      # Cloudinary configuration
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME:-dbzxfdul3}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY:-745719433317359}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET:-MDTCH37UjiuzhiZhZCtVtYpUcjY}
    volumes:
      - ./:/app
      - laninna_dev_data:/data
      - ./logs:/app/logs
    working_dir: /app
    command: ["air", "-c", ".air.toml"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  laninna_dev_data:
    driver: local

networks:
  default:
    name: laninna-dev-network