# 🦔 La Ninna - Fly.io Configuration

app = "laninna-hedgehog-app"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "5s"

# Use Dockerfile instead of buildpacks for consistency
[build]
  dockerfile = "Dockerfile"

# VM configuration for multiple regions
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
  
# Add secondary regions for better availability
[regions]
  primary = ["fra"]
  fallback = ["ams", "lhr"]
  
[metrics]
  port = 8080
  path = "/metrics"

[env]
  PORT = "8080"
  GIN_MODE = "release"
  DB_PATH = "/data/laninna.db"
  AUTO_MIGRATE = "false"
  FONTS_PATH = "./fonts"
  NOTIFICATION_INTERVAL_MINUTES = "30"
  EXPORT_MAX_RECORDS = "1000"
  REQUEST_TIMEOUT_SECONDS = "30"
  RATE_LIMIT_REQUESTS_PER_MINUTE = "100"
  # Cloudinary configuration
  CLOUDINARY_CLOUD_NAME = "dbzxfdul3"
  CLOUDINARY_API_KEY = "745719433317359"
  CLOUDINARY_API_SECRET = "MDTCH37UjiuzhiZhZCtVtYpUcjY"

# JWT_SECRET should be set via secrets
# fly secrets set JWT_SECRET=your-secret-value
# For production, consider setting Cloudinary credentials as secrets:
# fly secrets set CLOUDINARY_CLOUD_NAME=your-cloud-name
# fly secrets set CLOUDINARY_API_KEY=your-api-key
# fly secrets set CLOUDINARY_API_SECRET=your-api-secret

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[mounts]]
  source = "laninna_data"
  destination = "/data"

[processes]
  app = "./laninna-app"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

[deploy]
  release_command = "echo 'Deploying La Ninna Hedgehog App'"