# 🦔 La Ninna - Render Configuration

services:
  - type: web
    name: laninna-hedgehog-app
    region: frankfurt
    plan: starter
    runtime: go
    buildCommand: |
      go mod download
      go install github.com/swaggo/swag/cmd/swag@latest
      ~/go/bin/swag init
      go build -ldflags="-w -s" -o laninna-app .
    startCommand: ./laninna-app
    healthCheckPath: /health
    autoDeploy: true
    
    envVars:
      - key: PORT
        value: 8080
      - key: GIN_MODE
        value: release
      - key: DB_PATH
        value: /data/laninna.db
      - key: AUTO_MIGRATE
        value: true
      - key: JWT_SECRET
        sync: false
        # For production, set this via the Render dashboard or CLI
        # render secret set JWT_SECRET --value "your-secret-value"
      - key: NOTIFICATION_INTERVAL_MINUTES
        value: 30
      - key: EXPORT_MAX_RECORDS
        value: 1000
      - key: REQUEST_TIMEOUT_SECONDS
        value: 30
      - key: RATE_LIMIT_REQUESTS_PER_MINUTE
        value: 100
      - key: FONTS_PATH
        value: ./fonts
      # Cloudinary configuration (optional - for image uploads)
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
        # Set this via the Render dashboard or CLI
        # render secret set CLOUDINARY_CLOUD_NAME --value "your-cloud-name"
      - key: CLOUDINARY_API_KEY
        sync: false
        # Set this via the Render dashboard or CLI
        # render secret set CLOUDINARY_API_KEY --value "your-api-key"
      - key: CLOUDINARY_API_SECRET
        sync: false
        # Set this via the Render dashboard or CLI
        # render secret set CLOUDINARY_API_SECRET --value "your-api-secret"

    disk:
      name: laninna-data
      mountPath: /data
      sizeGB: 1