# 🦔 La Ninna - Render Configuration

services:
  - type: web
    name: laninna-hedgehog-app
    env: go
    region: frankfurt
    plan: starter
    runtime: go
    buildCommand: |
      # Use Go 1.22
      go mod download
      go install github.com/swaggo/swag/cmd/swag@latest
      ~/go/bin/swag init
      go build -ldflags="-w -s" -o laninna-app .
    startCommand: ./laninna-app
    healthCheckPath: /health
    autoDeploy: true
    
    envVars:
      - key: PORT
        value: 8080
      - key: GIN_MODE
        value: release
      - key: DB_PATH
        value: /data/laninna.db
      - key: AUTO_MIGRATE
        value: true
      - key: JWT_SECRET
        sync: false
        # For production, set this via the Render dashboard or CLI
        # render secret set JWT_SECRET --value "your-secret-value"
      - key: NOTIFICATION_INTERVAL_MINUTES
        value: 30
      - key: EXPORT_MAX_RECORDS
        value: 1000
      - key: REQUEST_TIMEOUT_SECONDS
        value: 30
      - key: RATE_LIMIT_REQUESTS_PER_MINUTE
        value: 100
      - key: FONTS_PATH
        value: ./fonts

    disk:
      name: laninna-data
      mountPath: /data
      sizeGB: 1

  - type: cron
    name: laninna-notifications
    env: go
    runtime: go
    schedule: "*/30 * * * *"
    buildCommand: |
      # Use Go 1.22
      go mod download
      go install github.com/swaggo/swag/cmd/swag@latest
      ~/go/bin/swag init
      go build -ldflags="-w -s" -o laninna-app .
    startCommand: ./laninna-app -task=notifications
    
    envVars:
      - key: GIN_MODE
        value: release
      - key: DB_PATH
        value: /data/laninna.db
      - key: JWT_SECRET
        sync: false
        # For production, set this via the Render dashboard or CLI
      - key: FONTS_PATH
        value: ./fonts
      - key: NOTIFICATION_INTERVAL_MINUTES
        value: 30